image: gitpod/workspace-go

tasks:
  - name: Init
    init: bundle install

vscode:
  extensions:
    - streetsidesoftware.code-spell-checker
    - streetsidesoftware.code-spell-checker-french
    - eamodio.gitlens
    - yzhang.markdown-all-in-one
    - Gruntfuggly.todo-tree

workspaceLocation:
  "."
